[keybinds]
left =  [ "Left" , "Ctrl+h" ]
down =  [ "Down" , "Ctrl+j" ]
up =    [ "Up"   , "Ctrl+k" ]
right = [ "Right", "Ctrl+l" ]

[system.monitor]
enabled = false

[weather]
enabled = false

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"
