[backdrop]
enabled = true
blur_intensity = 0.2
tint_intensity = 0.4

[bar.default]
background_opacity = 0.6
end = [ "tray", "notifications", "clipboard", "volume", "battery" ]
hover_highlight = true
margin_ends = 0
padding = 8
radius = 0
radius_bottom_left = 24
radius_bottom_right = 24
shadow = false
start = [ "control-center", "workspaces" ]
thickness = 24
widget_spacing = 8

  [bar.default.dead_zone.actions]
  right = "none"

[control_center]
hidden_tabs = [ "media", "weather" ]
show_shortcut_labels = false
width = 800

  [[control_center.shortcuts]]
  type = "wifi"

  [[control_center.shortcuts]]
  type = "bluetooth"

  [[control_center.shortcuts]]
  type = "caffeine"

  [[control_center.shortcuts]]
  type = "notification"

  [[control_center.shortcuts]]
  type = "power_profile"

  [[control_center.shortcuts]]
  type = "dark_mode"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

  [desktop_widgets.grid]
  cell_size = 16
  major_interval = 4
  visible = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0

  [idle.behavior.lock]
  action = "lock"
  enabled = true
  timeout = 600.0

  [idle.behavior.lock-and-suspend]
  action = "lock_and_suspend"
  enabled = true
  timeout = 1200.0

  [idle.behavior.screen-off]
  action = "screen_off"
  enabled = true
  timeout = 900.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

  [lockscreen_widgets.grid]
  cell_size = 16
  major_interval = 4
  visible = true

  [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
  box_height = 196.0
  box_width = 810.0
  cx = 960.0
  cy = 974.0
  output = "eDP-1"
  rotation = 0.0
  type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
    background_color = "surface_variant"
    background_opacity = 0.88
    background_radius = 12.0
    center_password_text = false
    input_opacity = 1.0
    input_radius = 6.0
    layout = "regular"
    show_caps_lock = true
    show_keyboard_layout = true
    show_login_button = true
    show_media = true
    show_session_buttons = true
    show_unlock_hint = true
    show_weather = true

  [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
  box_height = 128.0
  box_width = 512.0
  cx = 960.0
  cy = 140.0
  output = "eDP-1"
  rotation = 0.0
  type = "clock"

[notification]
background_opacity = 0.8
offset_x = 4
offset_y = 4

[osd]
enabled = false
background_opacity = 0.8
offset_x = 4
offset_y = 4
orientation = "vertical"
position = "center_right"
position_vertical = "center_right"

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[shell]
button_borders = false
card_borders = false
font_family = "GeistMono NF"
offline_mode = true
panel_anchor_bar = "default"
polkit_agent = true
popup_borders = false
popup_shadows = false

  [shell.launcher]
  categories = false

    [shell.launcher.providers.calculator]
    global = false
    prefix = "="

    [shell.launcher.providers.emoji]
    prefix = ""

  [shell.panel]
  borders = false
  shadow = false
  transparency_mode = "glass"

  [shell.screen_corners]
  size = 1

  [shell.screenshot]
  directory = "~/pictures/screenshots"
  filename_pattern = "Screenshot_%Y-%m-%d_%H%M%S"

[system.monitor]
enabled = false

[theme]
builtin = "Noctalia"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "soft"

  [theme.templates]
  builtin_ids = [ "btop", "gtk3", "gtk4", "kitty", "niri" ]
  enable_community_templates = false

[wallpaper]
directory = "~/pictures/wallpapers"
edge_smoothness = 0.0

  [wallpaper.automation]
  order = "alphabetical"

[weather]
enabled = false
