-- Hyprland Colors
-- Generated by Matugen, do not edit directly.

return {
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "0xff{{value.default.hex_stripped}}",
<* endfor *>
}
