$font_family = GeistMono Nerd Font

$surface = rgba(14131899) 
$on_surface = rgba(e6e1e9ff)
$surface_bright = rgba(3a383ecc)

general {
  ignore_empty_input = true
  immediate_render = true
  text_trim = true
}

background {
  monitor =
  path = ~/dotfiles/assets/_background.png

  blur_passes = 1
  blur_size = 3
}

shape {
  monitor =
  size = 640, 1080
  color = $surface

  halign = left
  valign = center
}

label {
  monitor =
  text = $TIME

  color = $on_surface
  font_family = $font_family
  font_size = 48

  position = -640, 172
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[] date +'%A, %d %B %Y'

  color = $on_surface
  font_family = $font_family
  font_size = 20

  position = -640, 114
  halign = center
  valign = center
}

image {
  monitor =
  path = /usr/share/sddm/faces/$USER.face.icon

  size = 160

  border_size = 1
  border_color = $surface_bright
  rounding = -1

  position = -640, -20
  halign = center
  valign = center
}

shape {
  monitor =
  size = 320, 60
  color = rgba(00000033)

  border_size = 1
  border_color = $surface
  rounding = -1

  position = -640, -154
  halign = center
  valign = center
}

label {
  monitor =
  text =   $USER

  color = $on_surface
  font_family = $font_family
  font_size = 16

  position = -640, -154
  halign = center
  valign = center
}

input-field {
  monitor =
  fade_on_empty = false
  hide_input = false

  outline_thickness = 1
  outer_color = $surface
  inner_color = rgba(00000033)

  placeholder_text = <i>Enter Password...</i>
  font_family = $font_family
  size = 320, 60

  dots_size = 0.2
  dots_spacing = 0.2

  position = -640, -238
  halign = center
  valign = center
}
