/* Quickshell Colors
 * Generated by Matugen, do not edit directly.
 */

import QtQuick

QtObject {
	<* for name, value in colors *>
		readonly property color {{name}}: "{{value.default.hex}}"
	<* endfor *>
}
