# @see https://wiki.hypr.land/Configuring/Environment-variables/ 

# Wayland
env = GDK_BACKEND,wayland,x11
# env = QT_QPA_PLATFORM,"wayland;xcb"
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Cursor
env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24

# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Electron apps
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# QT apps
env = QT_QPA_PLATFORMTHEME,gtk3

