# @see https://wiki.hypr.land/Configuring/Window-Rules

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
  name = floating-file-uploader
  match:class = .*
  match:title = ^(File Upload)(.*)$
  float = on
  center = on
  size = 640 480
}

windowrule {
  name = floating-volume-control
  match:title = ^(Volume Control)$

  float = on
  move = 1920-606 6
  size = 600 400
}

windowrule {
  name = floating-picture-in-picture
  match:title = ^(Picture-in-Picture)$

  float = on
  move = 1920-546 1080-310
  size = 540 304
}

windowrule {
  name = floating-rename-dialog
  match:class = thunar
  match:title = ^(Rename)(.*)$

  float = on
  move = center
  size = 400 150
}

windowrule {
  name = floating-lutris
  match:class = net.lutris.Lutris
  match:title = ^(Lutris)$

  float = on
  move = center
  size = 1000 600
}

workspace = 1, layout:dwindle
workspace = 2, layout:monocle
workspace = 3, layout:scrolling
